name: Qt C++ Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcrypto++-dev

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Build project
        run: |
          qmake
          make

      - name: Snyk monitor (C/C++ scan)
        run: snyk monitor --unmanaged --all-projects --org=rannez
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate SBOM
        run: syft . -o cyclonedx-json > sbom.json
